# Fake Database URL
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Tell Hibernate to use the H2 dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create the database tables based on your Java Models, then drop them when done
spring.jpa.hibernate.ddl-auto=create-drop